let level = 1;
let theme = 0;
let rows = 20;
let columns = 20;
let length = 20;
let map;
let canvas;
let pause = false;
let pauseButton;
let themeSelect;
let windowSpace = 0;
let darkMode = 0;
let darkModeP;
let dmSelector;
let themeLabel;
let settingsButton;
let direction = 0;
let initCol = 9;
let initRow = 9;
let snakeCol = initCol;
let snakeRow = initRow;
let timer = 500;
let score = 0;
let prefersDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;